project:
  type: book
  output-dir: docs
  resources:
    - "files/"
    - "favicon.ico"

book:
  title: "Unterlagen für das obligatorische Fach Informatik"
  author: "Jacques Mock Schindler"
  date: 2025-10-02
  date-format: DD.MM.YYYY

  chapters:
    - index.qmd
    - part: "Anleitungen"
      chapters:
        - files/lektionen_hs25/250628_speicher/speicherorganisation.qmd
        - files/lektionen_hs25/250702_systemeinrichtung/setup.qmd
    - part: "Einführung in Python"
      chapters:
        - files/lektionen_hs25/250901_probleme/probleme.ipynb
        - files/lektionen_hs25/250908_variablen/Variablen.ipynb
        - files/lektionen_hs25/250915_schlaufen/for_loop.ipynb
        - files/lektionen_hs25/250922_bedingungen/arbeitsblatt_bedingungen.ipynb
        - files/lektionen_hs25/251020_funktionen/funktionen.ipynb
        - files/lektionen_hs25/251027_funktionen/funktionen_2.ipynb
        - files/lektionen_hs25/251110_listen/listen.ipynb
        - files/lektionen_hs25/251124_dict/dict.ipynb
        - files/lektionen_hs25/251215_rekurisv/beurteilung_von_algorithmen.ipynb
        - files/lektionen_hs25/251215_rekurisv/rekursion.ipynb


  downloads: [pdf]
  navbar: 
    right: 
      - icon: github
        href: "https://github.com/SkriptenMk/I_eW_25-29/tree/main/files"
        aria-label: GitHub
        target: "_blank"
      - icon: bug
        href: "https://github.com/SkriptenMk/I_eW_25-29/issues"
        aria-label: "Fehler melden"
        target: "_blank"
    search: true

lang: de

format:
  html:
    theme:
      - cosmo
      - brand
      - custom.scss
    code-download: true
    toc: true
    # css: style.css
    code-line-numbers: true
  pdf:
    # Alle PDF-Einstellungen sind jetzt hier zentralisiert
    documentclass: scrreprt
    papersize: letter
    classoption: 
      - "DIV=11"
    number-sections: true
    toc: true
    top-level-division: chapter
    pdf-engine: xelatex
    crossref:
      chapters: true
    header-includes:
      - "\\KOMAoption{captions}{tableheading}"
    block-headings: true
    code-line-numbers: true
    break-at-whitespace: true



